// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/user': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/user.put').default>>>>
    }
    '/api/cos/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cos/auth').default>>>>
    }
    '/api/home/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/detail').default>>>>
    }
    '/api/home/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/notes.get').default>>>>
    }
    '/api/note/note': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/note.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/note.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/note.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/note.put').default>>>>
    }
    '/api/note/notebook': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/notebook.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/notebook.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/notebook.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/notebook.put').default>>>>
    }
    '/api/note/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/note/notes.get').default>>>>
    }
    '/api/notebooks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notebooks.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/uploadCos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploadCos.post').default>>>>
    }
    '/api/user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}